//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weights
    {
        public int Id { get; set; }
        public double Wyear { get; set; }
        public double WBaijia { get; set; }
        public double Wduplication { get; set; }
        public double WOffTime { get; set; }
        public double WcirculationFequency { get; set; }
    }
}
